# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown

kramdown:
  input: GFM

# Serve:
host:		     88.198.219.49		     

# Setup
title:               Luis Grangeia
tagline:             'A personal blog'
description:         ''

paginate: 5
paginate_path: "/page:num/"

gem 'github-pages', '170', group: :jekyll_plugins

gems:
  - jekyll-feed
  - jekyll-paginate

# About/contact
author:
  name:              Luis Grangeia
  url:               https://twitter.com/lgrangeia
  email:             luis.grangeia@gmail.com

